### ISSUE TITLE
Prepare repo and build scripts for the userscript

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/PopupBlocker#1]
The very first task is to create a repo with a userscript meta, empty script, and unit-tests.

Take a look here to get an example:
https://github.com/AdguardTeam/AdguardAssistant

### Build configurations

There should be three build configurations. The only difference is `downloadURL/updateURL` meta attributes.

* `dev` -- will be published to `gh-pages`
* `beta` -- will be published to `cdn.adguard.com/.../Beta`
* `release` -- will be published to `cdn.adguard.com`

### Unit-tests

Prepare a file with unit-tests.

### Travis-CI auto-build

Just like it's done in the Assistant repo: build, run unit-tests, publish dev build.

### Update README.md with the information on how to build and install the userscript.

**Comment by ameshkov** [comment]
@seanl-adg file the release draft in https://github.com/AdguardTeam/PopupBlocker/releases

**Comment by ameshkov** [comment]
@vbagirov please assist with the release notes.

Something like this:
```
This is the second release of Adguard's popup blocker userscript -- reworked from scratch and capable of handling modern popup scripts (unlike the first ver which was not updated for quite some time).

Please note, that it's fully functional in Chromium, and a bit limited in other browsers. We'll improve this in future versions.
```

**Comment by ameshkov** [comment]
@seanl-adg still need you to attach beta/release builds to the release notes.

**Comment by ameshkov** [comment]
@seanl-adg you should also update the `downloadURL/updateURL` as they will be published to a new directory:
```
https://cdn.adguard.com/public/Userscripts/AdguardPopupBlocker/2.0/....
https://cdn.adguard.com/public/Userscripts/Beta/AdguardPopupBlocker/2.0/....
```

**Comment by vbagirov** [comment]
@ameshkov @seanl-adg I've updated the draft (release notes), let me know if I missed anything.
