### ISSUE TITLE
Popup blocker script says it blocked the popup, still let's Microsoft Edge open a new tab

### ISSUE THREAD

**Issue by jppmarujo** [AdguardTeam/PopupBlocker#100]
## **Prerequisites:**
**Browser:** Microsoft Edge 42.17627.1000.0 
**System:** Windows 10.0.17627 · Version 1809 · Redstone 5 (Insider Skip Ahead Build) 
**Popup Blocker:** TamperMonkey with AdGuard Popup Blocker v2.1.10
**Adblocker:** AdGuard for Windows
**Filters:** Experimental, English, Portuguese, NoCoin 
**TamperMonkey scripts:** MrPiracy Player (other than Popup Blocker v2.1.10)

## **Steps to reproduce the issue:**

Using Microsoft Edge, navigate to https://proxyfl.info/ .
Click on the search box (you'll notice that there's like a fullscreen link over the actual webpage). 
When you click it, Popup Blocker will tell you it blocked a popup, but a new tab will still open, and stay opened, loading the ad content. The problem isn't really with the ad content loading, is the fact that that kind of layering bypasses the popup blocker script.

**Comment by seanl-adg** [comment]
Popup Blocker used to detect such clickable overlays and remove it, but in a bit lazy manner, i.e. when there is a user interaction with the page. There hasn't been a popup like this case that throws a clickable overlay in front of user unconditionally.

This popup uses some CSS tricks that bypasses our overlay detection logic, we will need to harden it.

**Comment by seanl-adg** [comment]
- Visit https://proxyfl.info/ with any browser with AG with a reasonable default setting
 - Clear every user settings on the page (cookies, localStorage, sessionStorage... details may be dependent on browser), and refresh the page
 - observe that the page creates a transparent overlay which changes the mouse cursor to "hand button"
   - click anywhere on the page, observe that a popup is blocked and an alert dialog is displayed, or
   - click on the search input field on the page, observe that a popup is blocked, and the input field is focused (text cursor is placed on the input field)

**Comment by jppmarujo** [comment]
Will try as soon as possible. Thank you for still working on this specific
issue, Sean.

2018-06-18 15:51 GMT+01:00 Sean Lee <notifications@github.com>:
