### ISSUE TITLE
A common "toast" notifications style

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/PopupBlocker#103]
Sometimes we need to provide the user with a feedback that does not require any actions.

I like the minimalistic approach of Android toast messages:
https://i.ytimg.com/vi/QoXvV2GAcek/hqdefault.jpg

We need to make our own android-like toast notifications module (reusable, in a new repo plz) and use it in a situation like this: https://github.com/AdguardTeam/PopupBlocker/issues/95#issuecomment-377499874

Here's an example of such a module:
https://www.cssscript.com/super-simple-javascript-message-toaster-toast-js/

@kaprielov please help with the default style:

1. Gray semi-transparent background
2. Font: default OS-dependent font (just like we use on the website)
3. Background border-radius at least 5px

**Comment by seanl-adg** [comment]
If it's not a complicated task, I'd include it (a toast-style notification or a balloon-style one) with the first release.

**Comment by ameshkov** [comment]
Ok, assigned it to the milestone

**Comment by seanl-adg** [comment]
https://github.com/AdguardTeam/PopupBlocker/commit/c77637aac61ab63792df59939fe36b975311cdd8
