### ISSUE TITLE
Exclusion can be created incorrectly

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/PopupBlocker#108]
Still works though.

STR:

1. Install PopupBlocker to Adguard for Win
2. Open http://testcases.adguard.com/PopupBlocker/test-popup-blocker.html
3. Reproduce any popup on the page
4. Click on "always allow %urlname%" (allow popups leading to evilsite.com)
5. Before the notification disappears open it and perform step "4" two more times.

Expected result:
{"whitelist":"[LString;evilsite.com"}

Actual result:
{"whitelist":"[LString;evilsite.com,evilsite.com,evilsite.com"}

Video:
https://uploads.adguard.com/up05_wc1mj.mp4

**Comment by seanl-adg** [comment]
For example, when a page `testcases.adguard.com/PopupBlocker/test-popup-blocker.html` is opened in a 2 separate tabs and whitelisting is done on both tab within a short time, it should not create a duplicate entry in the userscript storage.

**Comment by karina-archazh** [comment]
Checked, no duplicates.
