### ISSUE TITLE
ka-union.ru - false blocking

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/PopupBlocker#109]
### Issue URL (Incorrect Blocking)
[https://ka-union.ru/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fka-union.ru%2F)
### Comment
> Блокируются всплывающие окна при попытке авторизоваться через социальные сети

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/spkVeQF.png)
</details>

### System configuration

Information | value
--- | ---
Platform: | Win
AdGuard version: | 6.2
Pop-up Blocker: | 2.2.3
Browser: | Chrome
AdGuard driver: | WFP
Stealth mode options: | Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header from HTTP requests
Filters: | Russian,<br>English

**Comment by zzebrum** [comment]
can't repro on v7.0
