### ISSUE TITLE
plus.google.com - False positive

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/PopupBlocker#110]
STR:

1. Open https://plus.google.com/+DirtyUnicornsOfficial/posts/A9a1VEfn96y
2. Click on https://github.com/DirtyUnicorns/Notices on the page

Screenshot:
https://uploads.adguard.com/up05_l2kr8.png

2.2.3 Beta

**Comment by ameshkov** [comment]
Version? Priority?

**Comment by seanl-adg** [comment]
Added to default whitelist in https://github.com/AdguardTeam/PopupBlocker/commit/694c1261ce6e3a69acfaa8327c0fa2a6ae2254f2
