### ISSUE TITLE
ncw.livenation.com - website is broken

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/PopupBlocker#113]
AdGuard for Windows 6.3.1028.3331
AdGuard Popup Blocker 2.2.3/2.5.1

To reproduce go here - https://ncw.livenation.com/?c=LNMP_Promotions_NCW_LN.com_Carousel

Website is blank.
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/39533431-51021f58-4e2f-11e8-9b73-c83fe03b6ec3.png)

</details>
<br>

https://github.com/AdguardTeam/AdguardFilters/issues/15529

**Comment by seanl-adg** [comment]
Waiting for a working link

**Comment by aspasskaya** [comment]
Hi,
I cant repro this issue. (PopupBlocker 2.5.13)
@AdamWr  are problems still reproducible? Please, send a working link.

**Comment by AdamWr** [comment]
Hi,
This link was from this issue - https://github.com/AdguardTeam/AdguardFilters/issues/15529 and unfortunately I don't have idea how to get working link, so I think it can be closed.
