### ISSUE TITLE
litres.ru - false positive

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/PopupBlocker#114]
## Steps to reproduce

1. Open https://www.litres.ru/legkoe-chtenie/best/
2. Try changing a genre there: https://uploads.adguard.com/up04_95qga_Legkoe_chtenie__skachat_v_fb2_epub_txt_pdf_ili_chitat_onlain_besplatno_zhanr_g0.png
3. You'll see a popup blocker alert flickering in the corner of the page, but the page will be loaded anyways

**Comment by seanl-adg** [comment]
Should be fixed by https://github.com/AdguardTeam/PopupBlocker/commit/941bf504fbbc14cf69a7bae60c6c31a8214a532d

**Comment by seanl-adg** [comment]
Expected behavior:
 - Follow the instructions in the OP
 - A popup blocker alert dialog shouldn't appear in course of it
