### ISSUE TITLE
Fix Popup blocker pin button location

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/PopupBlocker#115]
It's too far from the screen border.
The position should be equal to Assistant's default position. (10 pixels, if I am correct)
#
<details><summary>Screenshot</summary>

<img width="357" alt="up04_0th1k_vladeltsy_proksi-serverov_dlya_telegram_smogut_dobavlyat_sponsorskie_kanaly_v_spiski_chatov_polzovatelei_" src="https://user-images.githubusercontent.com/17472907/40423430-3e0ad12a-5e9b-11e8-9532-60af65d19153.png">

</details>

**Comment by seanl-adg** [comment]
Fixed by https://github.com/AdguardTeam/PopupBlocker/commit/8f7d61904dcc68517a7b9a6d5f839e554492f8e3
