### ISSUE TITLE
popup site

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/PopupBlocker#117]
popup site
https://www.loldytt.com/Juqingdianying/SFDMM/
https://www.80s.ai/

**Comment by seanl-adg** [comment]
Thanks for reporting, I can reproduce the issue. 
Both websites use a transparent overlay, in a way similar to https://github.com/AdguardTeam/PopupBlocker/issues/100. We should improve our overlay-busting logic. 

In the meantime, you can add a rule `loldytt.com,80s.ai##body > a[target="_blank"][style*="z-index"]` to your adblocker to prevent popups on reported sites.
