### ISSUE TITLE
Implement the pop-up blocker warning alerts layout

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/PopupBlocker#12]
Here are the mockups of these alerts:
https://app.moqups.com/ameshkov/ZgAlYnihrU/view/page/aa9df7b72

@IldarKamalov use the same styles as in the new extension: https://monosnap.com/file/rM0L7wwtM4FZz7ySFxkwTtbDMelIrr

Alerts will be shown inside of an iframe (to not mess with the website's own styles), so just make alerts having full width/height inside of an iframe.

**Comment by IldarKamalov** [comment]
Markup for pop-up alerts
https://gist.github.com/IldarKamalov/3acd1abe983ab7e6889b81f08f94ab4b
