### ISSUE TITLE
Change the settings page domain to popupblocker.adguard.com

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/PopupBlocker#121]
GH pages domain is now changed to:
https://popupblocker.adguard.com/options.html

What it means:

1. You need to use it in the userscript code instead of `adguardteam.github.io`.
2. You need to supply an `index.html` page. For now (until we added a website page about PB) make a javascript redirect to `/options.html` there.
3. Change the `@homepage` to `https://popupblocker.adguard.com/`.
4. Change links in the README.md.

**Comment by seanl-adg** [comment]
Done in https://github.com/AdguardTeam/PopupBlocker/commit/672cbaf68558c78c4bfaba31fcfe7d9d68ffc5ce
