### ISSUE TITLE
gameforge.com is broken

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/PopupBlocker#122]
AdGuard for Windows 6.3.1154.3583
AdGuard Popup Blocker (Dev) 2.5.2

To reproduce go here - https://gameforge.com/

Website is broken.

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/41250757-23cfb484-6db8-11e8-8145-7b07fb916055.png)

</details>
<br>

I added `@@||gameforge.com^$extension` to English filter as a temporary solution, so please disable it before checking.

https://github.com/AdguardTeam/AdguardFilters/issues/17940

**Comment by seanl-adg** [comment]
This only affects the dev version.

**Comment by aspasskaya** [comment]
I cant repro this issue. Popup Blocker (Dev) 2.5.13
@AdamWr 
are problems still reproducible?
