### ISSUE TITLE
https://1740f665a91b68.com/ redirection problem

### ISSUE THREAD

**Issue by mozkan007** [AdguardTeam/PopupBlocker#123]
Hi,

Whenever I open yourporn.sexy website (sorry for opening an issue related to an adult site) there are some redirection and pop up problems like below;

https://362b643a66026e.com/
https://362b643a66026e.com/922072.html
https://362b643a66026e.com/afu.php?zoneid=1000715&var=922072
https://popunder.qualifyusers.com

When I click a video these redirections happen to me for the sites above. I hope you can fix it with the next release. Thanks.

Browser: Chrome v67 x64 latest
Script: Adguard Popupblocker v2.2.3

Edit:  https://362b643a66026e.com replaced by  https://1740f665a91b68.com/ . So the new trouble maker is https://1740f665a91b68.com/.

**Comment by seanl-adg** [comment]
Could you provide your configuration of adblockers? It seems that the website has several popups, but can't reproduce the one with 362b643a66026e.com url.

**Comment by mozkan007** [comment]
I am using Ublock Origin v1.16.10 with default settings and filters and also using Adguard Popupblocker on Tampermonkey v4.6. By the way, this problem occurs when I open this site after 1 or 2 days later so I mean when I do not enter this site for a while.

**Comment by mozkan007** [comment]
I solved my problem using Ublock element picker tool. Thank you for your attention.
