### ISSUE TITLE
[NSFW] vporn.com - missed popup

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/PopupBlocker#125]
https://github.com/AdguardTeam/AdguardFilters/issues/15782

Exclude `blatungo.com` before checking

AdGuard 6.3.1202.3679
PopupBlocker 2.2.3

**Comment by seanl-adg** [comment]
It seems that this is a concrete example of what I've been considering as https://github.com/AdguardTeam/PopupBlocker/issues/111
