### ISSUE TITLE
Popup blocker does not show an alert when there's a not translated string

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/PopupBlocker#128]
## Steps to reproduce

1. Install the dev build of the Popup Blocker
2. Switch AdGuard to the Russian language
3. Open http://testcases.adguard.com/PopupBlocker/test-popup-blocker.html
4. Use any test case there

## Expected result
An alert about a blocked popup with English strings used instead of not translated ones.

## Actual result
An error in the browser console: `Uncaught popup_text not localized`

**Comment by seanl-adg** [comment]
It only affects the dev version as I understand.

**Comment by ameshkov** [comment]
> It only affects the dev version as I understand.

Is there any difference in the way translations are applied?

**Comment by seanl-adg** [comment]
Yes, see: http://bit.adguard.com/projects/EXTENSIONS/repos/popup-blocker/pull-requests/41/commits/aa41a0f3a6ce59bcf87674a57146ac6795817b18#src/platform/userscript/get_message.ts

**Comment by ameshkov** [comment]
Got it

**Comment by seanl-adg** [comment]
Should be fixed with https://github.com/AdguardTeam/PopupBlocker/commit/43d1fa1290a47b71ce7ec898ba86b757191d7431
