### ISSUE TITLE
Popup blocker is not being detected on the HTTP options page

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/PopupBlocker#133]
## Steps to reproduce
1. Install the PB dev build
2. Open http://popupblocker.adguard.com/options.html

## Expected result
Popup blocker is detected

## Actual result
Popup blocker is not detected.

**Comment by vozersky** [comment]
I'd say this is a blocker, since you are always fowarded to http page when you click on "manage settings"

**Comment by seanl-adg** [comment]
Repository settings should be re-configured: https://help.github.com/articles/securing-your-github-pages-site-with-https/

**Comment by ameshkov** [comment]
Done

**Comment by karina-archazh** [comment]
Checked: Popup options page is available
