### ISSUE TITLE
Cannot save changes in Popup Blocker

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/PopupBlocker#141]
![image](https://user-images.githubusercontent.com/8361299/44899944-f1562400-ad0b-11e8-8a55-37a00c80bc2e.png)

**Comment by ameshkov** [comment]
The easiest way to fix this would be to start using the absolute URLs for resources.

**Comment by northis** [comment]
Resolved in `adguard-windows/pull-requests/190`

## Test instructions
1. Update AG to actual version
2. Try to edit the Popup Blocker's content. For example, add some text in a comment.
3. Save the script and ensure there is no error.
