### ISSUE TITLE
Beta build does not contain @exclude meta attributes

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/PopupBlocker#142]
The beta build should not be different from the release one. It's okay to not have `@exclude` attributes in the dev build (so that we could figure what false positives are there), but not for the beta build.

**Comment by northis** [comment]
Resolved in `popup-blocker/pull-requests/5`

## Test instructions
1. Update Popup Blocker to the actual version.
2. Make sure, this is beta version of Popup Blocker.
3. Make sure, that it contains `@exclude` strings.

**Comment by karina-archazh** [comment]
Checked: exclude strings are availible
