### ISSUE TITLE
Still popups on Rarbg site 

### ISSUE THREAD

**Issue by RohithKumarSp** [AdguardTeam/PopupBlocker#143]
it opens a new tab but malware bytes prevemts it from opening but it still opened a new tab 

it redirects in a new tab as shown below 

https://aaucwbe.com/sound?cver=1&refer=https%3A%2F%2Frarbgprx.org%2Ftop10&kw=%5B%22rarbg%22%2C%22index%22%2C%22page%22%5D&key=9ef78edf998c4df1e1636c9a474d9f47&scrWidth=1920&scrHeight=1080&tz=5.5&ship=&pst=&res=4.31&dev=r

**Comment by jppmarujo** [comment]
Maybe its the same method used in #100 ? Some kind of overlay that is clickable before we can click the actual webpage content.

**Comment by RohithKumarSp** [comment]
> Maybe its the same method used in #100 ? Some kind of overlay that is clickable before we can click the actual webpage content.

idk, but Pop up blocker for Chrome™ stops the pop up, but the reason i installed this script is so that i dont have to use Pop up blocker for Chrome™ .

**Comment by karina-archazh** [comment]
Can't reproduce this issue with Pop-up blocker 2.5.11

**Comment by Alex-302** [comment]
@karina-archazh a lot of popups are blocked by the filters, so check with disabled rules for this domain.
For example, in this case popup is blocked by our Pop-up blocker
![image](https://user-images.githubusercontent.com/8361299/48720770-09fa1a00-ec29-11e8-8e40-a04a9daf877b.png)

**Comment by karina-archazh** [comment]
On https://rarbgmirror.xyz/torrents.php? popup blocker doesn't block popups.
