### ISSUE TITLE
ssgdfm.com

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/PopupBlocker#144]
@adguard-bot commented on [Tue Sep 25 2018](https://github.com/AdguardTeam/AdguardFilters/issues/23005)

### Issue URL (Incorrect Blocking)
[http://www.ssgdfm.com/shop/main](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=http%3A%2F%2Fwww.ssgdfm.com%2Fshop%2Fmain)
### Comment
> There is no problem turning off the Adguard.
> When you turn on the Adguard, you will see two things: no connection and a white screen.
> --
> The information below is automatically generated. Do not delete it.
> 
> Referrer:
> http://www.ssgdfm.com/shop/main
> 
> Custom userscripts:
> https://cdn.adguard.com/public/Userscripts/AdguardAssistant/4.0/assistant.user.js
> https://cdn.adguard.com/public/Userscripts/AdguardPopupBlocker/2.2/popupblocker.user.js
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](http://res.cloudinary.com/adguard/image/private/s--WAyK5p-E--/v1537896988/iobjvd3ts6lflxep9hv6.png)
</details>

### System configuration

Information | value
--- | ---
Platform: | Win
AdGuard version: | 6.3.1399.4073
Browser: | Chrome
AdGuard driver: | WFP
Filters: | Filter unblocking search ads and self-promotion,<br>AdGuard Base,<br>(Obsolete) List-KR,<br>YousList,<br>AdGuard Spyware,<br>AdGuard Social Media,<br>AdGuard Japanese
Other extensions used: | windows10 home / chrome 69.0.3497.100 / window defender

**Comment by AdamWr** [comment]
Before checking please disable this rule from English filter:
`@@||ssgdfm.com^$extension`

**Comment by ameshkov** [comment]
Needs to be re-tested with PB 2.5.
If confirmed - exclude it in the manifest.

**Comment by northis** [comment]
Resolved in `popup-blocker/pull-requests/54`

**Comment by karina-archazh** [comment]
Checked: http://www.ssgdfm.com/shop/main is available
