### ISSUE TITLE
world.taobao.com is broken

### ISSUE THREAD

**Issue by freezewind** [AdguardTeam/PopupBlocker#149]
Website is broken.
AdGuard for Windows: 6.4.1739.4753
AdGuard Popup Blocker: 2.5.8
Brower: Firefox 56, Firefox 62 (IE and Chrome have no problem)
Website: [world.taobao.com](url)

<details>
  <summary>
    Screenshot of the website
  </summary>

![with PopupBlocker](https://user-images.githubusercontent.com/3954389/46710727-02912b00-cbfe-11e8-8c4b-f1712c8b4e32.jpg)
![without PopupBlocker](https://user-images.githubusercontent.com/3954389/46710732-0624b200-cbfe-11e8-91cf-fc6029a884d8.jpg)
</details>
<br />
Screenshot of the brower console
<details>
  <summary>
    Error with PopupBlocker
  </summary>

![error with PopupBlocker](https://user-images.githubusercontent.com/3954389/46710634-9e6e6700-cbfd-11e8-984c-fb8db3b15150.jpg)
</details>
<details>
  <summary>
Error without PopupBlocker
  </summary>

![error without PopupBlocker](https://user-images.githubusercontent.com/3954389/46710639-a0d0c100-cbfd-11e8-9ac5-a543786a861e.jpg)
</details>

**Comment by ameshkov** [comment]
@northis let's add `world.taobao.com` to exclusions real quick

**Comment by northis** [comment]
Resolved in `popup-blocker/pull-requests/56`
