### ISSUE TITLE
ksl.com

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/PopupBlocker#151]
@adguard-bot commented on [Fri Oct 26 2018](https://github.com/AdguardTeam/AdguardFilters/issues/24439)

### Issue URL (Incorrect Blocking)
[https://www.ksl.com/homes/listing/40260641](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.ksl.com%2Fhomes%2Flisting%2F40260641)
### Comment
Username: @klepper
> endless refresh cycle on ksl.com/homes 
> --
> The information below is automatically generated. Do not delete it.
> 
> Referrer:
> https://www.ksl.com/homes/listing/40260641
> 
> Custom userscripts:
> https://cdn.adguard.com/public/Userscripts/Beta/AdguardAssistant/4.2/assistant.user.js
> https://cdn.adguard.com/public/Userscripts/Beta/AdguardPopupBlocker/2.5/popupblocker.user.js
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/Arf9lal.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | Win
AdGuard version: | 6.4.1793.4861
Browser: | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.20 Safari/537.36
AdGuard driver: | WFP
Filters: | AdGuard Base,<br>Juvander's Adblock List for Finland,<br>AdGuard Dutch,<br>AdGuard Spanish/Portuguese
Other extensions used: | ublock, but disabled still same problem.

**Comment by zebrum** [comment]
can not repro on win.
but it's reproducible on mac with the rule enabled.. AG v2.0 though.

**Comment by northis** [comment]
Resolved in `pull-requests/59`
