### ISSUE TITLE
boards.4channel.org

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/PopupBlocker#154]
@adguard-bot commented on [Mon Dec 03 2018](https://github.com/AdguardTeam/AdguardFilters/issues/26431)

### Issue URL (Annoyance)
[NSFW][http://boards.4channel.org/tv/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=http%3A%2F%2Fboards.4channel.org%2Ftv%2F)
### Comment
Username: @efrancisco21
> Hi there, The adguard popup blocker is mistakenly blocking a legitimate popup on the site called 4chan.org / 4channel.org
> 
> How to reproduce: 
> 1. Go to a board for example 4chan.org/tv/ 
> 2. Try to report one of the posts or threads, to do this refer to the screenshot.
> 3. The result is that Adguard Popup Blocker would instead block the new window for the report form. The desired result is that Adguard Popup Blocker won't block the report form. 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/kRIhdiL.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/EDbCmYh.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | Win
AdGuard version: | 6.4
Browser: | Chrome
AdGuard driver: | WFP
Filters: | AdGuard Base,<br>AdGuard Spyware,<br>AdGuard Social Media
Other extensions used: | Internet download manager extension

**Comment by northis** [comment]
Resolved in `pull-requests/59`
