### ISSUE TITLE
cal-online.co.il

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/PopupBlocker#156]
@adguard-bot commented on [Thu Dec 13 2018](https://github.com/AdguardTeam/AdguardFilters/issues/26884)

### Issue URL (Incorrect Blocking)
[https://www.cal-online.co.il/self-service/prepaid/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.cal-online.co.il%2Fself-service%2Fprepaid%2F)
### Comment
Username: @ORI123456
> see that video
> https://youtu.be/U-s8SnLBly4
> --
> The information below is automatically generated. Do not delete it.
> 
> Custom userscripts:
> https://cdn.adguard.com/public/Userscripts/AdguardPopupBlocker/2.5/popupblocker.user.js
> https://cdn.adguard.com/public/Userscripts/AdguardAssistant/4.2/assistant.user.js
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/TcBxNLU.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/Xxnrh4g.png)
</details>

### System configuration

Information | value
--- | ---
Platform: | Win
AdGuard version: | 6.4.1814.4903
Browser: | Chrome
AdGuard driver: | WFP
Filters: | EasyList Hebrew,<br>AdGuard Base
Other extensions used: | Ext as default. Antivirus Eset internet security. No other as blockers

---

@ORI123456 commented on [Thu Dec 13 2018](https://github.com/AdguardTeam/AdguardFilters/issues/26884#issuecomment-446831675)

Same problem on another page on the site:
https://services.cal-online.co.il/Card-Holders/SCREENS/AccountManagement/Login.aspx?csrt=3560633927386473251&ReturnUrl=%2fcard-holders%2fScreens%2fAccountManagement%2fHomePage.aspx

Notice: 
After you will disable Adguard and refresh the page, even if you will enable adguard again, the problem won't occur. but if you will restart the browser the problem will be back

---

@Alex-302 commented on [Thu Dec 13 2018](https://github.com/AdguardTeam/AdguardFilters/issues/26884#issuecomment-446955558)

I can't reproduce. Is Stealth Mode enabled?

---

@ORI123456 commented on [Thu Dec 13 2018](https://github.com/AdguardTeam/AdguardFilters/issues/26884#issuecomment-446970053)

No, stealth mode disabled.

---

@Alex-302 commented on [Fri Dec 14 2018](https://github.com/AdguardTeam/AdguardFilters/issues/26884#issuecomment-447313967)

Which filter causes it?

---

@AdamWr commented on [Fri Dec 14 2018](https://github.com/AdguardTeam/AdguardFilters/issues/26884#issuecomment-447318795)

Could you please check these rules:
```
@@||services.cal-online.co.il/PrePaidCard/HomePage.aspx$extension
@@||services.cal-online.co.il/Card-Holders/SCREENS/AccountManagement/Login.aspx$extension
```
or try to disable AdGuard Popup Blokcer and check if it works.

---

@ORI123456 commented on [Fri Dec 14 2018](https://github.com/AdguardTeam/AdguardFilters/issues/26884#issuecomment-447327441)

The two options you propose, worked

---

@AdamWr commented on [Fri Dec 14 2018](https://github.com/AdguardTeam/AdguardFilters/issues/26884#issuecomment-447355779)

Ok, thank you for checking it.
So it seems that it's caused by AdGuard Popup Blokcer.
Added to AdGuard Base filter as a temporary solution:
```
@@||services.cal-online.co.il/PrePaidCard/HomePage.aspx$extension
@@||services.cal-online.co.il/Card-Holders/SCREENS/AccountManagement/Login.aspx$extension
```

**Comment by ORI123456** [comment]
Happen to me again. and after a bit of a time stopped to happen.

**Comment by northis** [comment]
The problem has nothing to do with Pop Up Blocker.
With these rules works fine, without - not. Suppose it is a filtering issue.

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/CoreLibs #667](https://github.com/AdguardTeam/CoreLibs/issues/667) via [**ZenHub**](https://www.zenhub.com/)

**Comment by AdamWr** [comment]
Maybe you are right, but I'm not able to reproduce that issue without Popup Blocker and it works fine on my end if I add `services.cal-online.co.il` to exclusion in Popup Blocker:
`// @exclude *://services.cal-online.co.il/*`

I checked it with these rules disabled:
`@@||services.cal-online.co.il/PrePaidCard/HomePage.aspx$extension`
`@@||services.cal-online.co.il/Card-Holders/SCREENS/AccountManagement/Login.aspx$extension`

AG for Windows 6.4 nightly
