### ISSUE TITLE
bs.to Pop Ups not blocked

### ISSUE THREAD

**Issue by xmaestro21** [AdguardTeam/PopupBlocker#158]
Issue URL 
bs.to

Comment
This site opens malicious Pop Ups when you click on any link there. I think it is Timer / Fingerprint based so it only happens once every 30-60 minutes. But amongst others it also opens a fake Microsoft Security warning Pop Up which you can't close easily.

I'm only using the Adguard Popup Blocker Script, without Adguard Adblocker. I hope you can help with this issue anyway.

System Information:

Platform: Windows 7 x64
AdGuard version: None (Adguard Pop Up Blocker Script is up-to-date)
Browser:  Chrome

**Comment by Alex-302** [comment]
We need the source page. 
Please write here:
https://github.com/AdguardTeam/AdguardFilters

**Comment by karina-archazh** [comment]
Hi @xmaestro21 
I run videos on this website over an hour in Chrome on Windows 7 and doesn't have any pop-ups.
Could you please send me some screenshots or maybe more info regarding this issue?

**Comment by xmaestro21** [comment]
@Alex-302 what do you mean by source page? the URL of the opened Popup?
I don't think adding it in the Adguard Filters would help me, because i don't use Adguard Adblocker like i said. Only the Popup Blocker Script

@karina-archazh when you are logged in there are no popups, OR when you have adguard adblock activated i think it gets blocked too. In my case i wanted to block the popup without using the adblocker, only with the popup blocker script.

So when you click anywhere on the site, a new tab with this url opens: 
`https://rotumal.com/afu.php?zoneid=1407888&var=1375561
`

and it redirects you to different ad pages. for example this here in the [screenshot](https://i.imgur.com/1jx9JY7.jpg): 

If the issue stil is not clear or it's not worth the effort, that's ok with me too. just wanted to ask if it's possible
thanks for your time

**Comment by Alex-302** [comment]
@xmaestro21 I mean where did it happen. I want to try to reproduce it.

**Comment by xmaestro21** [comment]
@Alex-302 i included the Website in my first post under "Issue URL" - it's "bs.to"

**Comment by Alex-302** [comment]
but it is empty, without any html

**Comment by xmaestro21** [comment]
https://bs.to/
you mean like this?

**Comment by Alex-302** [comment]
yes

**Comment by xmaestro21** [comment]
Sorry i should have typed the complete URL from the beginning, i'll know better next time

**Comment by karina-archazh** [comment]
@xmaestro21
