### ISSUE TITLE
www.zippyshare.com - popup not blocked

### ISSUE THREAD

**Issue by AzimsTech** [AdguardTeam/PopupBlocker#160]
AdGuard Popup Blocker 2.5.12
Tampermonkey 4.7.63
AdGuard DNS-over-TLS

**Steps to reproduce:**

1. Open this website - https://www62.zippyshare.com/v/Or0886Hi/file.html
2. Click on "Download Now" button, the first popup is not blocked

**Comment by zzebrum** [comment]
@AzimsTech sorry, file has expired. What browser do you use?

**Comment by AzimsTech** [comment]
@zzebrum Chrome

Try this new link: https://www20.zippyshare.com/v/9ipsGnme/file.html
