### ISSUE TITLE
Popup Blocker extension breaks amoma.com

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/PopupBlocker#162]
@slavaleleka commented on [Tue Feb 19 2019](https://github.com/AdguardTeam/AdguardForWindows/issues/2435)

### Steps to reproduce
1. Choose one of [hotels on amoma.com](https://www.amoma.com/city.php?key=201903122019031912050000205000020500000000023094&tar=00000)
2. Open photo
3. Click "right" for next one

<h3><details>
<br/>

<summary>Actual behavior:</summary>

![2019-02-19 3](https://user-images.githubusercontent.com/45171506/53028511-0ec4a900-3478-11e9-9db1-977f808a6839.png)

![2019-02-19 5](https://user-images.githubusercontent.com/45171506/53028521-15532080-3478-11e9-874c-e0b9260d3d7a.png)

</details></h3>

### Your environment
* AdGuard 7.0.2198 (CL 1.3.153)
* Chrome 72
* Windows 10

**Comment by timirila1** [comment]
The site is not available anymore.
