### ISSUE TITLE
indoxxi.bz

### ISSUE THREAD

**Issue by 3xploiton3** [AdguardTeam/PopupBlocker#163]
https://indoxxi.bz/movie/alita-battle-angel-2019-8kbf

i found this rule can block in adblocker, 
`||jomys.xyz^$popup`

pls add to popupblocker script

**Comment by Alex-302** [comment]
Not reproduced.
Blocked ad near player.

**Comment by 3xploiton3** [comment]
what does it mean?

**Comment by Alex-302** [comment]
I can't reproduce popup. Maybe you clicked on empty banner.

**Comment by 3xploiton3** [comment]
i used from tampermonkey script, how to add spanish filter?

**Comment by Alex-302** [comment]
Install AdGuard:)
