### ISSUE TITLE
AG PB is Simplified Chinese interface when choosing browser default in the Tampermonkey's language setting.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/PopupBlocker#167]
@ameshkov
@northis

Before, I didn't check the interface of AG popup blocker...
Today, I install it in Tampermonkey.
Even if you compile zh-TW locale file, you still wrongly use Simplified Chinese (zh or zh-CN) for Traditional Chinese (zh-TW) interface.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/XNWBp6c.png)
</details><br/>

// ==UserScript==
// @name AdGuard Popup Blocker

Simplified Chinese (简体中文) (Usually it should be zh-CN, but you used zh.)
// @name:zh AdGuard 弹窗拦截器

Traditional Chinese (繁體中文 or 正體中文) (zh-TW)
// @name:zh-TW AdGuard 彈出式視窗封鎖器

Please fix it.

I ever suggested to modify zh to zh-CN, otherwise your developers will feel confused.
https://github.com/AdguardTeam/PopupBlocker/issues/159

Well, you only use my Traditional Chinese translation for its title on greasyfork.org.
https://greasyfork.org/zh-TW/scripts/33396-adguard-popup-blocker

**Comment by lancelot-moon** [comment]
@northis
May you also check the language interface for Web of Trust?

// @description:zh 在用户体验基础上浏览任何名誉网站和安全信息。 <- Simplified Chinese (zh-CN)
// @description:zh-TW 根據用戶的體驗檢查任何的網站在信譽和安全資訊方面。 <- Traditional Chinese (zh-TW)

Maybe it's the same mistake.

**Comment by northis** [comment]
You use Tampermonkey to test PB. We will check it, but if you try PB & WOT with AG (not Tampermonkey ), it will use the same language as AG.

**Comment by lancelot-moon** [comment]
Here, it's still PB v2.5.11.
https://greasyfork.org/zh-TW/scripts/33396-adguard-popup-blocker

I went to AG GitHub for PB v2.5.12.
In the Tampermonkey's language setting, if I choose "**Browser Default**", PB v2.5.12 will be **Simplified Chinese**.
After I choose "Chinese (Traditional)" in the Tampermonkey's language setting, PB v2.5.12 is Traditional Chinese.
It's strange since my chrome is Traditional Chinese by default.

How to check the language interface of PB in AG for Windows?
I have checked the language interface of WoT v1.1.9 is Traditional Chinese.

BTW, I wish to update their translations.

Thanks.

**Comment by lancelot-moon** [comment]
@northis
Do you have idea why AG PB is Simplified Chinese interface when choosing browser default in the Tampermonkey's language setting?
My browser default should be zh-TW.

(AG PB shows correct language interface according to AG for Windows.)

**Comment by tvinzz** [comment]
@lancelot-moon, what is your version of Tampermonkey?
try to replace `zh-TW` with `zh_TW` in userscript and test it.

**Comment by tvinzz** [comment]
@lancelot-moon

**Comment by lancelot-moon** [comment]
@tvinzz 
I don't use Tampermonkey now.
Just ma have a bug for browser default in the Tampermonkey's language setting.

**Comment by tvinzz** [comment]
I tested via Tampermonkey browser extension and Adguard application.
Cannot reproduce.
