### ISSUE TITLE
Google reCAPTCHA

### ISSUE THREAD

**Issue by Alexey71** [AdguardTeam/PopupBlocker#168]
Google reCAPTCHA incorrect working. Version script 2.5.12
Test site https://basketbuild.com/signup and other 

![68747470733a2f2f7265706f7274732d696d672e616467756172642e636f6d2f685573334766752e706e67](https://user-images.githubusercontent.com/10572914/54092172-06d29780-439a-11e9-8490-2208b7c0059e.png)

**Comment by Alexey71** [comment]
Original theme https://github.com/AdguardTeam/AdguardFilters/issues/30779

**Comment by aspasskaya** [comment]
I cant repro this particular issue. 
@Alexey71 are problems still reproducible?

**Comment by Alexey71** [comment]
latest version 2.5.13 fixed
