### ISSUE TITLE
Speedometer performance

### ISSUE THREAD

**Issue by choco** [AdguardTeam/PopupBlocker#181]
I was just testing my browser javascript interpreter with https://browserbench.org/Speedometer2.0/ and noticed a drop in performance when using AdGuard. After some investigation I found out that the culprit is the PopupBlocker extension. If this is enabled I see a drop of more than 20 (to the result value).
I'm not sure if this is expected, if speedometer hits a particular special case or if this is a performance issue that can be worked on, but at least I wanted to hear your opinions on the issue.

I'm using Safari in my tests, and tried the PopupBlocker extension loaded both with TemperMonkey and the native AdGuard app for Mac and got the same performance issues.

**Comment by ameshkov** [comment]
Yeah, Popup Blocker overrides some of the native browser APIs so it can have a negative effect on such tests. We'll look for ways to mitigate it.
