### ISSUE TITLE
Please stop moving outmoded translations from onesky to Crowdin.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/PopupBlocker#185]
@aalpatkina 
Last week, I found that some English phrases are outmoded in the project of popup blocker.
Of course, the translations for those outmoded English phrases are also unmatched with the new phrases on Crowdin.

Last week, I manually fixed my translations on Crowdin.
Yesterday, you deleted those English phrases (including my translations) and anew added English phrases without translations on Crowdin.
I also anew filled in my translations.
I think it's better to let translators manually fix the translations.

Today, I found Tim Shenin (tsenin) again moved outmoded translations from onesky to Crowdin.
He moved outmoded translations to overwrite my fixed translations.
May you stop moving outmoded translations from onesky to Crowdin?
Thanks.

**Comment by ameshkov** [comment]
@timirila1 have we finished with the popup blocker migration?

**Comment by timirila1** [comment]
@lancelot-moon @ameshkov sorry for the inconvenience. Popup-blocker phrases in the process of moving from onesky, so it may be not stable at now. I plan to finish with it today.

**Comment by lancelot-moon** [comment]
The issue is:
1. The phrases in popup blocker at developer side are newer.
You didn't sync the newer phrases to onesky in the past.

2. So some of translations in popup blocker are outmoded.
I suggest to let translators manually fix.

onesky:
Allow pop-ups on {$origDomain}
Crowdin:
Allow pop-ups for {$origDomain}

onesky:
List of exceptions is empty
Crowdin:
List of allowed sites is empty

onesky:
Exceptions
Crowdin:
Allowed

onesky:
List of websites with silenced notifications is empty
Crowdin:
List of silenced sites is empty

onesky:
Popups will be allowed on websites listed here.
Crowdin:
Popups will be allowed for domains listed here.

onesky:
Blocked popups notifications will not be shown on websites listed here.
Crowdin:
Notifications for blocked popups will not be shown for domains listed here.

onesky:
Step 3: Refresh this page to **get to** the userscript settings <- Please keep this.
Crowdin:
Step 3: Refresh this page to get the userscript settings <- x

onesky:
If you have AdGuard for Windows installed, you can ignore this step as the Popup Blocker userscript comes pre-installed.
Crowdin:
If you installed AdGuard for Windows, you can ignore this step as the Popup Blocker userscript comes pre-installed.

onesky:
First of all, to use a userscript you need a special program **or extension that can run** userscripts. <- Please keep this.
Crowdin:
First of all, to use a userscript you need a special program that runs userscript. <- x

onesky:
**Popup Blocker** aborted a script execution to prevent background redirect <- Please keep this.
Crowdin:
PopupBlocker aborted a script execution to prevent background redirect <- x

onesky:
Popup Blocker cannot run on this domain
Crowdin:
Popup Blocker is disabled for this domain

Some phrases exist on onesky but not on Crowdin.
ex:
onesky:
Blocked an attempt to open a {{0_url}} pop-up window
Crowdin:
No the phrase

**Comment by lancelot-moon** [comment]
May you fix the 3 phrases on Crowdin?
The original 3 phrases on onesky are correct.
Thanks.

onesky:
Step 3: Refresh this page to get to the userscript settings <- Please keep this.
Crowdin:
Step 3: Refresh this page to get the userscript settings <- x

onesky:
First of all, to use a userscript you need a special program or extension that can run userscripts. <- Please keep this.
Crowdin:
First of all, to use a userscript you need a special program that runs userscript. <- x

onesky:
Popup Blocker aborted a script execution to prevent background redirect <- Please keep this.
Crowdin:
PopupBlocker aborted a script execution to prevent background redirect <- x

**Comment by timirila1** [comment]
@lancelot-moon Thanks for your comments, the last one should be fixed.

**Comment by lancelot-moon** [comment]
The last one?
Do you only mean PopupBlocker -> Popup Blocker?

Will `Step 3: Refresh this page to get to the userscript settings`  and `First of all, to use a userscript you need a special program or extension that can run userscripts.` be kept?
Thanks.

**Comment by timirila1** [comment]
@lancelot-moon I mean all of these cases should have been updated in crowdin.

> Step 3: Refresh this page to get to the userscript settings
> First of all, to use a userscript you need a special program or extension that can run userscripts.
> Popup Blocker aborted a script execution to prevent background redirect

**Comment by lancelot-moon** [comment]
First of all, to use a userscript you need a special program or extension that runs userscript.
-> First of all, to use a userscript you need a special program or extension that runs **userscripts**.

Thanks, no other problem.
