### ISSUE TITLE
There should be a way to revert whitelisted domains

### ISSUE THREAD

**Issue by seanl-adg** [AdguardTeam/PopupBlocker#19]
Otherwise, users have to uninstall and reinstall their userscript.
It could be done by a dedicated settings pane.

**Comment by ameshkov** [comment]
Btw, for AG I suggest adding a "Storage" link to the userscript, so that people could examine/edit what's inside of the GM storage.

**Comment by ameshkov** [comment]
That would do as a temporary solution: https://github.com/AdguardTeam/AdguardForWindows/issues/1893

The final solution would be to implement settings pane (assigned to v2.2)
