### ISSUE TITLE
Foil overlays

### ISSUE THREAD

**Issue by seanl-adg** [AdguardTeam/PopupBlocker#2]
http://www.itdmusic.com/2017/07/planit-hank-finish-him-feat-styles-p-conway-the-machine-lil-fame-single-itunes-plus-m4a.html

A popup script, when not blocked, generates an overlay having `z-index: 2147483647` on each of page's links, which seem to be disappearing only when certain popups are opened, making links unusable.

**Comment by The-Commissioner** [comment]
@seanl-adg Since you have put this for review, shall I try it?

**Comment by seanl-adg** [comment]
@The-Commissioner Hi, it is still in a premature stage. Once an actual userscript file (of a form `.user.js`) is deployed in `gh-pages` branch you can try it.

**Comment by The-Commissioner** [comment]
@seanl-adg Ok, I thought I could have manually created a text file with the code and then rename it as in .user.js format and then manually install by browsing in the Extensions module. 👅

**Comment by seanl-adg** [comment]
You can do it, then you need to concatenate files `meta.js` file and `index.js`, and add a line `@grant none` in the meta block.

**Comment by The-Commissioner** [comment]
Hmm..I tried that but maybe I was wrong somewhere(as there was still 1 popup), so I'll wait for you guys to compile.

But one thing I would like to point out is for you guys to check it's compatibility with the inbuilt popupblockers that browsers come up with.
Like in Firefox: about:preferences#content
There is a Block Popup Option. So who overpowers who, becomes an important question I think.
The result was different with that option checked and then unchecked.
I'm sure Chrome also has a block popup  option(but that's not my daily browser).

Just my 2 cents. :)

**Comment by seanl-adg** [comment]
It is already meant to be supplementary for browser's own popup blockers.

Most popups are triggered when you click somewhere on the page -- they do not, for example, automatically show popups after a predefined time is passed. This is because such popups will be blocked by browser's built-in popup blocking features.

Current userscript uses this fact that there is always a 'user input' when a browser tries to open a new window. It examines how this 'user input' is being processed to decide whether to open a new window or not.
