### ISSUE TITLE
Make build process more modular

### ISSUE THREAD

**Issue by theseanl** [AdguardTeam/PopupBlocker#20]
Build process is constantly being complicated, I need to make it more organized. I have to bundle up 2 sources separately, one to run on the page's context and the other to run on userscript hosts' sandboxed context (to use `GM_getValue` api). Below are build task components:
   - Using 2 bundlers (rollup, closure compiler) depending on build channels.
   - Applying preprocess to each of them.
   - Replacing resources placeholder in source files to a respective resources. Currently there is one resource.

**Comment by seanl-adg** [comment]
@ameshkov Can this be closed now?

**Comment by ameshkov** [comment]
Yep
