### ISSUE TITLE
astrogo.astro.com.my

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/PopupBlocker#210]
@adguard-bot commented on [Fri Apr 24 2020](https://github.com/AdguardTeam/AdguardFilters/issues/54297)

### Issue URL (Incorrect Blocking)
 [https://astrogo.astro.com.my/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fastrogo.astro.com.my%2F)
### Comment
Username: @sweejin
> I was able to replicate the same/exact problem with the same screen shots on two other Windows 10 PC, and another iMac/macOS. I know it's probably unrelated, but I have AdGuard Pro installed on my iPhone XS, and had no issues login in; but that's a completely different platform. 
> 
> --
> The information below is automatically generated. Do not delete it.
> 
> Referrer:
> https://astrogo.astro.com.my/
> 
> Custom userscripts:
> https://userscripts.adtidy.org/release/assistant/4.3/assistant.meta.js
> https://userscripts.adtidy.org/release/popup-blocker/2.5/popupblocker.meta.js
> https://userscripts.adtidy.org/release/adguard-wot/1.0/wot.meta.js
> https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.meta.js
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/s2Uxzig.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/YT7fn1U.jpg)
</details>
<details>
  <summary>Screenshot 3</summary>

  ![Screenshot 3](https://reports-img.adguard.com/JIStevA.jpg)
</details>
<details>
  <summary>Screenshot 4</summary>

  ![Screenshot 4](https://reports-img.adguard.com/IJDh623.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | Mac
AdGuard version: | 2.3.2.710 release
Browser: | Safari
Stealth mode options: | Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header from HTTP requests, Strip URLs from tracking parameters, Self-destructing third-party cookies (180), Block Push API, Block Location API, Block Java
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances<br/><br/><b>Language-specific:</b><br/> AdGuard Russian, <br/>AdGuard German, <br/>AdGuard Japanese, <br/>AdGuard Dutch, <br/>ABPindo, <br/>EasyList China, <br/>EasyList Italy, <br/>Official Polish filters for AdBlock, uBlock Origin & AdGuard
Custom filter subscriptions: | 
Other extensions used: | As far as I can see, there is none running, and remember I have long uninstalled all ad blockers. I have never installed anti-virus for my MacBook.

**Comment by AdamWr** [comment]
It seems that it's caused by Popup Blocker.
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/80196834-2b311800-861e-11ea-93ef-89e683e4a83c.png)

</details>

Before checking it, please disable this rule (from Base filter):
`@@||astrogo.astro.com.my^$extension`

**Comment by sweejin** [comment]
Hey AdamWr,

I tried looking for that rule under Base filter, but I couldn't find it. I did remove it from the User rules filter. The problem is still there after I reloaded the page. 

I'm sorry, I'm kinda new to this, I don't understand / how to read the codes in the console. 

How should I proceed?

**Comment by AdamWr** [comment]
Hello,

Did you update filters?
If not, then please open AdGuard app, click on update button (marked on a screenshot below), restart web browser and check if you can still reproduce this issue.

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/80237907-c5fd1700-865d-11ea-8023-223a45bd092d.png)

</details>

**Comment by sweejin** [comment]
Oooooh.... I see. I have to update filters. My macOS version of AdGuard settings seem a bit different, but after I clicked "Check for Filter Updates", it works now! Thanks very much.

**Comment by AdamWr** [comment]
I don't have macOS, so on this screenshot is AdGuard for Windows.
I'm glad that it works.
Thank you for your reply.
