### ISSUE TITLE
Malware-like?

### ISSUE THREAD

**Issue by Hyoretsu** [AdguardTeam/PopupBlocker#216]
I don't know how tf, but all of a sudden a window about popups started appearing, with AdGuard written in it. I haven't installed anything in more than a month, and yet it just appeared on my Chrome.

**Comment by ameshkov** [comment]
Could you please take a screenshot and attach it here?

**Comment by zzebrum** [comment]
@Hyoretsu clearing cache in the browser should help with this.

**Comment by Hyoretsu** [comment]
@zzebrum Found it. There's a script called "AdGuard Popup Blocker" on my Tampermonkey. But the fact still stands that I'm 100% sure I didn't install this, especially because it was last updated 2 weeks ago, when I last messed with Tampermonkey a few months ago. And even then, I only manually added a few scripts for Cookie Clicker. Uninstalled.
