### ISSUE TITLE
findicons.com - broken website 

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/PopupBlocker#218]
Steps to reproduce
1. Disable this rule (from Base filter):
`@@||findicons.com^$extension`
2. Go here -  [https://findicons.com/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://findicons.com/)

Website is broken.

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/94349439-ad49c080-0044-11eb-9ec4-ed74adc6e380.png)

</details>

**Comment by AdamWr** [comment]
It seems that it still not work (if this rule is disabled - `@@||findicons.com^$extension`) and I guess because script is minified and looks like this:
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/117448935-a4589000-af3f-11eb-8a59-e4255798b489.png)

</details>

If I'm not wrong, website is broken due to that `__REACT_DEVTOOLS_GLOBAL_HOOK__.renderers` is undefined.

Probably similar issue occurs here - https://github.com/AdguardTeam/PopupBlocker/issues/234

**Comment by AdamWr** [comment]
As far as I understand this website has been excluded from AdGuard Popup Blocker script, I guess it's fine.
But I suppose that similar issue may also occurs on another websites as well, maybe I don't understand something, but I think this part from this commit - `https://github.com/AdguardTeam/PopupBlocker/commit/47f67aa777d58c036f50d9d23264f31018a58b85` shouldn't be minifed.

I mean that script in AdGuard for Windows looks like this:
```
if (!oa.call(window, "__REACT_DEVTOOLS_GLOBAL_HOOK__")) {
        var Nb = 0,
        Ob = {
            Ea: new Map,
            Ga: !0,
            U: function () {
                return Nb++
            },
            Da: function () {},
            Ba: function () {},
            Ca: function () {}
        };
```

If I modify it to:
```
if (!oa.call(window, "__REACT_DEVTOOLS_GLOBAL_HOOK__")) {
        var Nb = 0,
        Ob = {
            renderers: new Map,
            supportsFiber: !0,
            inject: function () {
                return Nb++
            },
            onScheduleFiberRoot: function () {},
            onCommitFiberRoot: function () {},
            onCommitFiberUnmount: function () {}
        };
```
then website works fine even if it's not excluded, the same for this issue - https://github.com/AdguardTeam/PopupBlocker/issues/234

**Comment by mohamed-seada-1994** [comment]
I hope this solve your issue #240
