### ISSUE TITLE
NextJS App is broken if React Dev Tools is not installed

### ISSUE THREAD

**Issue by mohamed-seada-1994** [AdguardTeam/PopupBlocker#219]
- AdGuard Popup Blocker 2.5.13
- The cause of this problem is the solution introduced for https://github.com/AdguardTeam/PopupBlocker/issues/119 which create a dummy function for preact compatibility
- possible solution is adding more props for __REACT_DEVTOOLS_GLOBAL_HOOK__
- Screenshots
![NextJS-React-DevTools](https://user-images.githubusercontent.com/27208846/95655240-285fac00-0b06-11eb-9cbe-11f9b70f3647.png)

**Comment by mohamed-seada-1994** [comment]
#218 is causee for the same reason

**Comment by ameshkov** [comment]
@mohamed-seada-1994 please check the beta version: https://userscripts.adtidy.org/beta/popup-blocker/2.5/popupblocker.user.js
