### ISSUE TITLE
Pop ups when clicking Top right

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/PopupBlocker#228]
URL:  https://dizigang.com/

Steps to solve the problem:
Add this: dizigang.com##.pageskin

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/AdguardFilters #71598](https://github.com/AdguardTeam/AdguardFilters/issues/71598) via [**ZenHub**](https://www.zenhub.com/)

**Comment by wout-codes** [comment]
@ameshkov What is ZenHub used for?

**Comment by ameshkov** [comment]
@wout-codes we're using it internally to manage Github issues across different repos
