### ISSUE TITLE
Popup Blocker is not compatible with PLAY mobile Dashboard login

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/PopupBlocker#233]
Site: https://24.play.pl/Play24/Welcome
Issue: redirect loop with `EMPTY RESPONSE` code when Popup Blocker Script running in background. 
Whitelisting domains does not work as workaround here.

**Comment by FadeMind** [comment]
CC @ameshkov @TheHasagi

**Comment by FadeMind** [comment]
@tvinzz  sorry, but exclude domains did not work here. Loop with EMPTY RESPONSE ERROR still exists when Popup Blocker is active. 
I have installed latest script version.

**Comment by tvinzz** [comment]
@FadeMind, please try v2.5.38

**Comment by FadeMind** [comment]
@tvinzz now works. Thanks. 
![20210426-1619448340-001](https://user-images.githubusercontent.com/9846948/116102599-224ea880-a6af-11eb-82f4-c9a0403187c6.png)
