### ISSUE TITLE
portalpasazera.pl 

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/PopupBlocker#237]
Redirect from https://portalpasazera.pl to https://bilet.wielkopolskiebilety.pl/koszyk after click `KUP BILET` ( buy a ticket) does not work when Adguard Popup Blocker works. 

This is official site PKP search engine with many service providers. 

Reproduce:
Select any FROM and DESTINATION . Click on selected time > `KUP BILET` (buy a ticket). 
Should be open new site with wizard. 
It is but as `about:blank` with no redirect to main wizard site. 

@AdamWr

**Comment by zzebrum** [comment]
@FadeMind on which OS?

**Comment by FadeMind** [comment]
@zebrum Windows 10 x64 + Edge Chromium +Adguard Extension + Violentmonkey + PopupBlocker JS

**Comment by tvinzz** [comment]
fixed in v2.5.53
