### ISSUE TITLE
online.bfgruppe.de

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/PopupBlocker#238]
# Remove `@@||online.bfgruppe.de^$extension` after fixing.

@adguard-bot commented on [Mon May 31 2021](https://github.com/AdguardTeam/AdguardFilters/issues/84511)

### Issue URL (Incorrect Blocking)
 [https://online.bfgruppe.de/v3/index.csp#/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fonline.bfgruppe.de%2Fv3%2Findex.csp%23%2F)
### Comment
Username: @andy-kl
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/prekvP2.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/H65at4G.jpg)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Windows v7.6.1
Browser: | Chrome
AdGuard driver: | WFP
Stealth mode options: | Hide your search queries, <br>Remove X-Client-Data header from HTTP requests, <br>Strip URLs from tracking parameters, <br>Self-destructing third-party cookies (2), <br>Disable cache for third-party requests, <br>Block Push API, <br>Block Location API, <br>Block Flash, <br>Block Java, <br>Hide your Referrer from third-parties (217.237.150.188)
DNS filtering: | server: `quic://dns.adguard.com`<br>filters: `User rules`
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base<br/><br/><b>Privacy:</b><br/> Fanboy's Anti-Facebook List, <br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> Fanboy's Social Blocking List, <br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> Adblock Warning Removal List, <br/>AdGuard Annoyances<br/><br/><b>Security:</b><br/> NoCoin Filter List<br/><br/><b>Other:</b><br/> AdGuard Experimental<br/><br/><b>Language-specific:</b><br/> Latvian List, <br/>AdGuard German
Userscripts: | https://userscripts.adtidy.org/release/assistant/4.3/assistant.user.js,<br>https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.user.js,<br>https://userscripts.adtidy.org/release/popup-blocker/2.5/popupblocker.user.js
Referrer: | [217.237.150.188](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=217.237.150.188)

**Comment by AdamWr** [comment]
It seems that it's similar/the same issue as here - https://github.com/AdguardTeam/PopupBlocker/issues/218#issuecomment-838837862

**Comment by tvinzz** [comment]
fixed and merged
