### ISSUE TITLE
Think about a proper way to apply whitelist/blacklist and display domains

### ISSUE THREAD

**Issue by seanl-adg** [AdguardTeam/PopupBlocker#25]
using domains are not enough, domain for `about:blank` and `data:text/html,base64;...` will be counted as `""`.
Also, we should determine what string to show in alert. Currently a full url is being shown, however for example we can trim it to domain only.

**Comment by ameshkov** [comment]
Can't you check `window.top` location?

**Comment by seanl-adg** [comment]
What matters here are domains of popup windows. It is necessary to somehow represent `about:blank` and `data:text` urls.

**Comment by ameshkov** [comment]
I suggest you can use the website's own domain as a stub in this case

**Comment by seanl-adg** [comment]
no, whitelisting/blacklisting works based on destination url, there is no website's own domain
