### ISSUE TITLE
learn-anything.xyz

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/PopupBlocker#254]
**Issue URL (Incorrect Blocking)**: https://learn-anything.xyz/programming/software-development/build-automation

<details><summary>Screenshots:</summary>

https://i.imgur.com/rb5G58B.png

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/141497551-099fafbf-933f-44c7-956a-f88fc1bcb5d5.png)
</details><br/>

**Comment by chirag127** [comment]
Why closed

**Comment by maximtop** [comment]
Url was added in exclusions https://github.com/AdguardTeam/PopupBlocker/commit/feae253105e4ab396394f0cb36ee640270bc74e7
