### ISSUE TITLE
There should be a way to suppress alerts

### ISSUE THREAD

**Issue by seanl-adg** [AdguardTeam/PopupBlocker#26]
Some sites, e.g. https://www.iwatchonline.cr/tv-shows/58490-wynonna-earp, tries to open popups on each clicks. Such issues can be resolved by emulating a successful popup, but it is not a reliable solution and we should provide an option like `silence domain`, `disable notifications (altogether)`

**Comment by ameshkov** [comment]
Duplicate of existing issues, we've added these options as a part of the redesign.
