### ISSUE TITLE
Website broken - programme.tvb.com/jade

### ISSUE THREAD

**Issue by Thomasc5** [AdguardTeam/PopupBlocker#265]
Link: https://programme.tvb.com/jade

When Popup Blocker is enabled, it breaks the page:
![enable](https://user-images.githubusercontent.com/5540385/159153609-91bd8511-60a1-4399-96d2-077a79253e76.JPG)

When Popup Blocker is disabled, browser renders the page correctly:
![disable](https://user-images.githubusercontent.com/5540385/159153636-eade1569-7388-465d-8a45-8c52da038694.JPG)

p.s. This applies to all the links under https://programme.tvb.com/
-------------------------------------------------
AdGuard Popup Blocker	2.5.67
Tampermonkey v.4.15
Google Chrome v. 99.0.4844.74

**Comment by stanislav-atr** [comment]
@Thomasc5, hi! I've checked the issue and it seems that website is broken regardless of our products (turned off AdGuard adblocker, extra and popupblocker). Could you please check again without any third-party extensions?
