### ISSUE TITLE
How to add outlook (web/pwa) in whitelist?

### ISSUE THREAD

**Issue by mariohik** [AdguardTeam/PopupBlocker#269]
I'm trying to download an attachment, but it keeps me asking to block the popup.
How can add the app to whitelist?
![image](https://user-images.githubusercontent.com/38980017/166505328-4730808c-ae12-47c4-be7d-23168f74ee28.png)

**Comment by maximtop** [comment]
Hi, we add websites to whitelist ourselves.

**Comment by withinpipo** [comment]
I have the same issue even if I read that you fixed it 5 days ago. Unable to download attachments from Outlook web

**Comment by tvinzz** [comment]
@withinpipo, the issue is fixed. Update is coming soon.
