### ISSUE TITLE
Event delivery issue on tugaflix.com

### ISSUE THREAD

**Issue by seanl-adg** [AdguardTeam/PopupBlocker#27]
http://tugaflix.com/Filme?F=4633690
It is almost impossible to use the site. Clicking anywhere triggers 2-3 blocked popup notifications, and it requires a lot of click to 'click' on the video player's play button. Also doubleclick or text selection does not work.

**Comment by Alex-302** [comment]
popups are blocked by the rules
https://github.com/AdguardTeam/AdguardFilters/commit/c03346afb4bff5ef5cd868e7406d8c86af7869d2

**Comment by Alex-302** [comment]
popups are blocked by the rules
https://github.com/AdguardTeam/AdguardFilters/commit/20bf23127e610c12bb941c0658cb24351549e9ba
