### ISSUE TITLE
Auto-updating between versions

### ISSUE THREAD

**Issue by TPS** [AdguardTeam/PopupBlocker#273]
I think this is some weird standard for userscripts that I never understood (is it meant for security?), but this 1 doesn't update properly, either, presumably because of the version being embedded in the path.  Could there be additionally a canonical address (like https://userscripts.adtidy.org/beta/popup-blocker/latest/popupblocker.user.js or https://userscripts.adtidy.org/release/popup-blocker/latest/popupblocker.user.js) that'd actually allow auto-updating to work?

**Comment by zzebrum** [comment]
reopen if needed

**Comment by zzebrum** [comment]
wrong issue 🙈

**Comment by zubrRB** [comment]
В версии `7.12 nightly 8` при проверке обновления фильтров выдаёт ошибку у Блокировщика всплывающей рекламы. 

<details><summary>Screenshot:</summary>

![oshibka](https://user-images.githubusercontent.com/50718960/213138594-69e9a183-09c2-4a2f-9a13-10f96612cebc.png)
</details><br/>

**Comment by zubrRB** [comment]
https://github.com/AdguardTeam/AdguardForWindows/issues/4574

**Comment by maximtop** [comment]
Actually, there are such links. And you can find them in the readme section of https://github.com/AdguardTeam/PopupBlocker#installation. 
The userscript would be updated along with the filters.
Please feel free to reopen this issue if you have other questions.

**Comment by TPS** [comment]
@maximtop This seems correct ifF y'all stay @ v2.5.x .…  What happens when you change the version or URL convention?

**Comment by maximtop** [comment]
We would specify a new link in the manifest for updates.

**Comment by TPS** [comment]
See, that's the point of a canonical link.  Just like for the filter lists, a permanent link, irrelevant of version, is useful to avoid having to update settings.
