### ISSUE TITLE
Adguard Popup Blocker Notification Options Blank

### ISSUE THREAD

**Issue by maximtop** [AdguardTeam/PopupBlocker#279]
@Watanuki-kun commented on [Thu Oct 27 2022](https://github.com/AdguardTeam/AdguardForWindows/issues/4460)

### Steps to reproduce

1. Go to a website where the adguard popup blocker is triggered.
2. Click on the Options button in the adguard popup blocker notification.
3. In the dropdown, the selections are empty or run out of bounds of the window.

### Expected behavior

Should show adguard popup options such as allowing the popup.

### Actual behavior

Shows blank options

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/17272769/230582589-4b74f4de-9544-441a-8ee1-a48523a727f7.png)

</details>

### Customer ID 

Adguard Ticket 670734
### Your environment

* Environment name and version: (e.g. Chrome 59) Edge 106.0.1370.52 (Official build) (64-bit)
* Operating system and version: (e.g. Windows 10, v.1703, build 15063.413) Windows 11, 21H2 ,build 22000.1098

---

@maxikuzmin commented on [Fri Oct 28 2022](https://github.com/AdguardTeam/AdguardForWindows/issues/4460#issuecomment-1295103469)

 @Watanuki-kun what site do you see this notification on? what are the steps to reproduce?

---

@Watanuki-kun commented on [Fri Oct 28 2022](https://github.com/AdguardTeam/AdguardForWindows/issues/4460#issuecomment-1295161728)

1. Go to https://www.jamesallen.com/
2. In the top right-hand corner in the site navigation bar, click on the person icon to log in.
![image](https://user-images.githubusercontent.com/2594415/198680152-fd679943-3b86-4ed1-8e8a-07b31f583317.png)
4. A window will display asking for login details. Below that, it will state "or sign in with" and have a facebook and google image below. I click on the google image icon and that is when the adguard popup notification will display.
![image](https://user-images.githubusercontent.com/2594415/198679846-612ff78d-668d-4ac2-a63e-cf77bad38c18.png)

---

@maxikuzmin commented on [Mon Oct 31 2022](https://github.com/AdguardTeam/AdguardForWindows/issues/4460#issuecomment-1297380970)

@Watanuki-kun you're right. Issue in the works

**Comment by maximtop** [comment]
@kodiakhub, could you please open a new issue?

**Comment by AdamWr** [comment]
I think that it might be related to - https://github.com/AdguardTeam/PopupBlocker/issues/250
