### ISSUE TITLE
`Manage preferences` option is broken

### ISSUE THREAD

**Issue by kodiakhub** [AdguardTeam/PopupBlocker#284]
After clicking `Manage preferences...` the redirected address `popupblocker.adguard.com/options.html` is not working properly.

<details><summary>Screenshot</summary>
<p>

![SS](https://user-images.githubusercontent.com/56846906/214998199-ecd80775-833b-4609-83f9-2c1c0b7fcdd8.png)

</p>
</details>

- Tampermonkey v4.18.1
  - AdGuard Popup Blocker v2.5.76
    - [Test here](https://tezgoal.com/menu-tezgoal/channels/live/tezgoal?watch=Bein+Sports+1+FR)

**Comment by stanislav-atr** [comment]
@kodiakhub , hi! Thank you for feedback, this will be fixed in the closes release.

**Comment by stanislav-atr** [comment]
1. Go to http://example.org/
2. Run `document.documentElement.addEventListener("click", () => window.open(`/test`) );` in console
3. Click anywhere on the page to trigger popup
4. Try opening settings

also, do you use some other userscripts/extensions that could interfere?

**Comment by stanislav-atr** [comment]
```
Entering the command in the console tab gave an error:
```
formatting broke the code, my bad:
`document.documentElement.addEventListener("click", () => window.open("/test") );`

It seems that `izleorg3.org#%#//scriptlet("prevent-window-open")` rule is being applied on the page, successfuly blocking settings. If you prefer using popupblocker, you may disable this rule with `izleorg3.org#@%#//scriptlet("prevent-window-open"`.
