### ISSUE TITLE
Can not userscript settings fetched

### ISSUE THREAD

**Issue by tkp206093** [AdguardTeam/PopupBlocker#286]
Tampermonkey BETA 4.19.6175
AdGuard Popup Blocker 2.5.76

Microsoft Edge 109.0.1518.78
<img width="901" alt="image" src="https://user-images.githubusercontent.com/29872453/216787370-0353fe2b-7efb-4787-a8d9-fbbdc43dac68.png">

**Comment by stanislav-atr** [comment]
@tkp206093, hi! Thank you for feedback, this will be fixed in the closes release.
