### ISSUE TITLE
AdGuard Popup Blocker Beta doesn't work in Firefox

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/PopupBlocker#289]
Steps to reproduce:
1. Install AdGuard Popup Blocker (Beta) version 2.5.85
2. Open Firefox (in Chrome it works correctly)
3. Go to - https://example.org/
4. Run in browser console:
```js
document.documentElement.addEventListener("click", () => window.open(`/test`) );
```
5. Click anywhere

Popup should be blocked, but it looks like that there is an error.
This error seems to occurs on any website, so it looks like that there is something wrong with user script in Firefox.

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/232225391-9905f744-c4ae-48af-8ea4-d1063959d2d2.png)

</details>

Stable version of AdGuard Popup Blocker works fine.

**Comment by contribucious** [comment]
:eyes: Same here too.

Indeed, I needed to manually add the stable version in my **AG for Windows (nightly)** and disabling the beta one temporarily. :relaxed:

**Comment by maximtop** [comment]
Thank you. Did you update to the new beta version manually?

**Comment by AdamWr** [comment]
AdGuard Popup Blocker Beta is part of the AdGuard for Windows nightly build, so I think that it has been updated automatically.

**Comment by contribucious** [comment]
For my part, either automatically or … following a `Check for filter updates…` (which also updates the extensions), used frequently lately (to update in an immediate way my LAN custom filters).

**Comment by contribucious** [comment]
Manually updated to the new beta version `2.5.86` and … looks like it's indeed fixed. ✔️

##### Thank you for your quickness! 👍
