### ISSUE TITLE
Error updating scripts

### ISSUE THREAD

**Issue by hieuck** [AdguardTeam/PopupBlocker#301]
![image](https://github.com/AdguardTeam/PopupBlocker/assets/30469654/dac40011-9ff1-486c-99b8-0693d3b40a96)
tôi đã thử cài đặt lại, đã thử trên trình duyệt khác nhưng kết quả cũng không hết thông báo lỗi 
I tried reinstalling, tried on another browser but the error message still didn't go away

**Comment by hieuck** [comment]
![image](https://github.com/AdguardTeam/PopupBlocker/assets/30469654/8c9bcc04-56ed-41e4-9d16-acbe8e23a6fe)
có phải vấn đề đã được sửa?
Has the problem been fixed?

**Comment by stanislav-atr** [comment]
@hieuck, hi! The error is due to a broken icon link in the userscript's metadata, and it normally should not block userscript updates (for Tampermonkey, it does not). The PopupBlocker Beta with a fix is on the way and will be shortly followed by a release version.

**Comment by stanislav-atr** [comment]
@hieuck this should now be fixed in beta v2.5.93, looking forward to your feedback.
