### ISSUE TITLE
Popups attached to anchor, input tags

### ISSUE THREAD

**Issue by theseanl** [AdguardTeam/PopupBlocker#31]
https://forum.adguard.com/index.php?threads/resolved-mp3fiber-com-anti-adblock-windows.24559/
topboard.org

Such websites attach event listeners on anchor or input submit buttons. When a user clicks on such elements, it calls `window.open` with an ad url, or swaps the original href attribute to ad url and call `window.open` with the original href.

I have to think about what we can do to block those; I suppose, no user interaction is meant to trigger 2 navigations at once, and any such attempt is an undue abuse of APIs. We may use this as a guiding principle in detecting unwanted popups.

**Comment by seanl-adg** [comment]
Related issue: https://forum.adguard.com/index.php?threads/linkshrink-net.26805/
