### ISSUE TITLE
Pop up

### ISSUE THREAD

**Issue by Jokopentil** [AdguardTeam/PopupBlocker#311]
https://www.google.com/search?q=Proliga+yolla+2024&ie=UTF-8#ip=1
![Screenshot_2024-04-19-16-35-33-37_4d38fce200f96aeac5e860e739312e76.jpg](https://github.com/AdguardTeam/PopupBlocker/assets/114223791/3fb88f7b-c44d-422d-bbc6-89a0e37ae616)

**Comment by Jokopentil** [comment]
![Screenshot_2024-04-19-16-35-18-73_4d38fce200f96aeac5e860e739312e76.jpg](https://github.com/AdguardTeam/PopupBlocker/assets/114223791/1a57fd53-534f-430e-bb8d-70b664f44b1e)

**Comment by alexx7311** [comment]
@Jokopentil Hello! Do you have Popup Blocker installed in some kind of userscript manager or in the AdGuard app?
Please describe the problem in as much detail as possible, reproduce the problem and take a screenshot.

**Comment by Jokopentil** [comment]
Yes violenmonkey
And i use pop up blocker script adguard

**Comment by alexx7311** [comment]
@Jokopentil What problem have you encountered? Please describe it in detail.

**Comment by Jokopentil** [comment]
I think this link is tracking
Because this link direct to gambling
But in this web whrited sport article
So i hope you block it

Pada Sel, 23 Apr 2024 17.09, alexx7311 ***@***.***> menulis:

**Comment by Jokopentil** [comment]
On the website it was written about sports, but when you opened it, you looked at it and it redirected you to a gambling site
![Screenshot_2024-04-23-17-24-58-69_4d38fce200f96aeac5e860e739312e76.jpg](https://github.com/AdguardTeam/PopupBlocker/assets/114223791/c9008b3d-41ac-4f45-bc93-ebc145dba51c)

**Comment by alexx7311** [comment]
@Jokopentil Our filters team says it's out of scope for popup blocker, it should blocks popups opened in new tab/window, but on [ednasa-ci.com](http://ednasa-ci.com/) there is just redirection to another website.

There is no content on this website, but if you just want to block this redirection you can use this rule:
`ednasa-ci.com#%#//scriptlet('abort-current-inline-script', 'Array', 'window.location')`

You can paste it in User rules section of AdGuard Browser extension.
