### ISSUE TITLE
Exclude all websites that tinyShield is executed

### ISSUE THREAD

**Issue by piquark6046** [AdguardTeam/PopupBlocker#316]
https://github.com/List-KR/tinyShield/issues/1

**Comment by slavaleleka** [comment]
@piquark6046 where the list can be found?

**Comment by piquark6046** [comment]
https://github.com/AdguardTeam/PopupBlocker/issues/316#issuecomment-2482365584
In `sources/banner.txt` of [tinyShield userscript](https://github.com/List-KR/tinyShield/)

**Comment by windwak3r** [comment]
@piquark6046, hello! Please describe step by step how to reproduce the problem.

**Comment by piquark6046** [comment]
1. Install tinyShield 1.1.0
2. Install AdGuard Popup Blocker
3. Visit https://dogdrip.net
