### ISSUE TITLE
[Feature request] Trigger log

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/PopupBlocker#38]
Think about implementing some kind of a history log that stores information about the recently blocked pop-ups: 

 - original page URL;
 - destination page URL;
 - timestamp;
 - maybe an option to whitelist either of the websites (original/destination).

Partly this is needed in order to circumvent the problem when the pop-up is blocked as you follow a link to another page. The notification will not be shown on the new page.

**Comment by ameshkov** [comment]
Any idea for the UI?

**Comment by vbagirov** [comment]
Only an idea so far. I'll try to saturate this task with more details later, alongside the milestone.
