### ISSUE TITLE
Make sure that popular popup scripts are handled

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/PopupBlocker#4]
Original issue:
https://github.com/AdguardTeam/AdguardForWindows/issues/1851

```
http://www.hdsector.com/
http://www.itdmusic.com/
https://www.djmaza.life/
```

**Comment by seanl-adg** [comment]
The userscript in the master branch works all popups when tested with Chrome 61 on my end. It misses a lot on Firefox due to browser api limitations described in https://github.com/AdguardTeam/PopupBlocker/issues/5. It misses Popads popups in Edge.

**Comment by seanl-adg** [comment]
Those were used to be testing pages for the popup blocker, but I can't reproduce popups on above mentioned sites anymore. This is a generic aspect of popup ads, websites hosting them tends to change a lot.

**Comment by zzebrum** [comment]
can't reproduce
