### ISSUE TITLE
ur.ly

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/PopupBlocker#42]
Adguard 6.2.400
Popup Blocker 2.1.7
Sample URL: http://ur.ly/xW5vmeM
Another e.g: http://ur.ly/xDRGQ00
Popups on the site after clicking on generating URL, getting link after timer(5seconds).
And after that it's not redirecting(this maybe a filter issue, not sure though).
Happens in both Chrome and firefox stable releases.

**Comment by seanl-adg** [comment]
This issue is essentially https://github.com/AdguardTeam/PopupBlocker/issues/31. I am currently thinking about how to deal with such issues, I will take this issue into account.
