### ISSUE TITLE
Install directly into Mac Desktop?

### ISSUE THREAD

**Issue by BioBoostedOne** [AdguardTeam/PopupBlocker#44]
The notes imply this can be installed directly into the Mac desktop app.  Can it?  I know you can use TamperMonkey for Safari.  The Desktop v1.5 does not use this v2.1 blocker, correct?  Does the desktop blocker even work?

**Comment by seanl-adg** [comment]
As I understand, the Mac desktop app supports userscripts. @ameshkov could you please provide a detailed answer?

**Comment by ameshkov** [comment]
Mac apps do have a hidden support of userscripts, but we don't allow installing custom userscripts yet.

Eventually, once we migrate the Mac app to the new AdguardTeam/CoreLibs engine, it will be possible.

**Comment by thealjey** [comment]
@ameshkov has this situation changed since 2017?
are custom userscripts supported now?

**Comment by ameshkov** [comment]
Sure, settings -> extensions.

**Comment by thealjey** [comment]
@ameshkov
I'm sorry, I don't understand
everything is already enabled there, there is no PopupBlocker extension on the list, and I do not see how to add a custom script
it only allows to install additional extensions from the App Store

**Comment by ameshkov** [comment]
Are you using [AdGuard for Mac](https://adguard.com/en/adguard-mac/overview.html)? It's quite different from AdGuard for Safari from the app store.

**Comment by thealjey** [comment]
oh, I didn't know about that one :)
thank you!
