### ISSUE TITLE
Missed page replication in code.ptcong.com

### ISSUE THREAD

**Issue by theseanl** [AdguardTeam/PopupBlocker#45]
In http://code.ptcong.com/demos/bjp/demo.html?type=tabunder, a popunder script replicates the page to a new tab, and navigates the parent tab to a new page. However, this is currently undetected, and the second line of defense, `beforeunload` event handler is triggered. Also, replicating a link url is not detected.

**Comment by seanl-adg** [comment]
Should be fixed by https://github.com/AdguardTeam/PopupBlocker/commit/43d1fa1290a47b71ce7ec898ba86b757191d7431, although `preventDefault` is not being prevented for now. This is a separate issue to be dealt with.

**Comment by seanl-adg** [comment]
- Visit http://code.ptcong.com/demos/bjp/demo.html?type=tabunder with the latest PB installed with any browser
 1. Click anywhere on the page, observe that a popup is blocked and the page stays the same (no additional alerts are displayed, no page navigation occurs), or
 2. Click on the "A normal link", observe that a popup is blocked and the page stays the same, or
     - Ideally, we should restore the original behavior, which is to follow the link's url, but this is a separate issue
 3. Click on the "A link with target=_blank", observe that a popup is blocked and the page stays the same

**Comment by karina-archazh** [comment]
Checked
