### ISSUE TITLE
Missed a couple of pop-ups on http://www.kephyr.com/popupkillertest/

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/PopupBlocker#47]
Report:
https://forum.adguard.com/index.php?threads/adguard-popup-blocker-issues.25720/

**Comment by im3or** [comment]
Yes, even this one - http://www.popuptest.com/popuptest6.html

**Comment by seanl-adg** [comment]
Both  http://www.kephyr.com/popupkillertest/test/test12.html and http://www.popuptest.com/popuptest6.html are not popups that we block. Those are just absolutely positioned `div`s.
