### ISSUE TITLE
Implement alternative popup detection mechanism

### ISSUE THREAD

**Issue by seanl-adg** [AdguardTeam/PopupBlocker#5]
The current method almost does not work in FF, because FF does not support `window.event`, and retrieving event via `Function.caller` is not reliable, because it cannot be used in `strict mode` and can't handle recursions in the call stack. An alternative mechanism will provide much benefit for such cases.

**Comment by ameshkov** [comment]
Assigned to v2.1. Let's make the very first release compatible with Chrome

**Comment by The-Commissioner** [comment]
I have felt this across repositories here, firefox always get second-hand treatment :-(

**Comment by ameshkov** [comment]
This time it's due to FF's limitations, it does not provide any viable alternatives so we are forced to use some [dangerous tricks](https://github.com/AdguardTeam/PopupBlocker/pull/11) in order to make it work with FF.

**Comment by The-Commissioner** [comment]
uBlock is able to block popups, ABP is able to block popups within the same firefox, so I don't understand it.

And still if that is not possible then atleast fix the popup modifier.

**Comment by ameshkov** [comment]
This has nothing to do with the $popup modifier. This repo is about generic approach to block popular popups scripts, so that we didn't even need to craft custom rules.

**Comment by The-Commissioner** [comment]
Yes it has nothing to do with popup modifier but since you are atm not able to provide any solution for firefox users, that's why the fix was suggested above.  That would give firefox users atleast something to work with.

**Comment by ameshkov** [comment]
Oh, I don't say we won't provide the FF solution, we'll just do it later as it is more complicated. Before merging that pull request we want to be sure that the simple solution works as it should so that we could use it as a basis and compare the FF solution with it.

**Comment by The-Commissioner** [comment]
In case of adguard later is just too much later....
And as of this moment FF users will neither have the popup blocker userscript nor the modifier.
Thus, I said FF here gets second-hand treatment.

**Comment by ameshkov** [comment]
> In case of adguard later is just too much later....

I wouldn't be that pessimistic, the pull request is waiting to be merged.

**Comment by The-Commissioner** [comment]
I learnt that from my experience here, gave up Adguard DNS because of that, ADG Win followed next and now looks like it's Android's turn.

**Comment by ameshkov** [comment]
@seanl-adg 
1. The new pop-up blocker causes significant issues with gmail and twitter
2. Gmail initial load is very slow
3. Twitter just hangs
