### ISSUE TITLE
Wrong behavior of the PopupBlocker inside of an UWP app

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/PopupBlocker#50]
https://forum.adguard.com/index.php?threads/6-2-424-2123-beta-linkedin-win-10-app-new-pop-up-blocker-blocking-all-external-links.25840/

**Comment by ameshkov** [comment]
First of all, we don't really need popup blocker inside of any UWP app. Can we detect that it is the case?

**Comment by seanl-adg** [comment]
Javascripts in UWP apps have access to special apis through a global `Windows` object. Accoding to https://docs.microsoft.com/en-us/uwp/api/windows.ui.popups.messagedialog, it seems that we may use `Windows.UI.Popups.MessageDialog` as a replacement for `window.confirm`.

**Comment by ameshkov** [comment]
I don't get it, why should we try to block pop-ups inside of an UWP app in the first place?

**Comment by seanl-adg** [comment]
I assumed that some popup/popunder scripts can work inside of UWP apps because `window.open` is supported. This is why the original issue was possible.

**Comment by ameshkov** [comment]
In theory, yes, but I've never seen any real example and I doubt we should try to protect people from a theoretical threat.

**Comment by ameshkov** [comment]
Also, I doubt using a popup script inside of a UWP app complies with the MS Store terms.

**Comment by seanl-adg** [comment]
I just installed a UWP app called "Monument browser" ([store link](https://www.microsoft.com/ko-kr/store/p/monument-browser/9nblggh1nsvj) and tried applying Popup Blocker with AdGuard for Windows. The popup blocker still works, although it misses some popups that is blocked with, say chrome. `window.confirm` does not work in this browser, so whitelisting is broken in this browser.

**Comment by seanl-adg** [comment]
Fixed in https://github.com/AdguardTeam/PopupBlocker/commit/31750b4a49a67517c07e4d3f120ca0f28ae5ee67
