### ISSUE TITLE
Exclude the most popular websites in the release build

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/PopupBlocker#51]
Source:
https://forum.adguard.com/index.php?threads/adguard-for-windows-v6-2-424-beta.20710/page-8#post-156107

He has a point actually. While we want to collect the feedback on false positives, it makes sense to do it in beta/dev builds and to exclude the most popular websites in the release build.

At least these:
google
gmail
yahoo
bing
linkedin
facebook

**Comment by seanl-adg** [comment]
Excluded google, linkedin, facebook from release build in https://github.com/AdguardTeam/PopupBlocker/commit/31750b4a49a67517c07e4d3f120ca0f28ae5ee67
