### ISSUE TITLE
Dev build of the popup blocker breaks XenForo forums

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/PopupBlocker#52]
For instance, on AdGuard Forum when it is enabled, I cannot post anything inside of a conversion or in the forum thread.

The input box in the "reply" area is invisible.

I have popup blocker installed via ViolentMonkey btw.

**Comment by ameshkov** [comment]
Here is the error I see in the browser console:
https://uploads.adguard.com/up04_knh11_AdGuard_DNS_rules__AdGuard_Forum.png

**Comment by seanl-adg** [comment]
Fixed in https://github.com/AdguardTeam/PopupBlocker/commit/a64651a1576b6cc2c1667aef5ee1869bdd52a7f7
