### ISSUE TITLE
A 'popup blocked' notification appears despite the new tab opens anyway

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/PopupBlocker#57]
Example: https://vk.com/comssru

Screenshot:
<details>

![image](https://uploads.adguard.com/vbagirovtngd6.png)
</details>

When you click on this link, you are taken to the comss.ru website (new tab), but there's also a notification about the blocked popup.

**Comment by seanl-adg** [comment]
Here is what is happening: the page `https://vk.com/comssru` intercepts click events, perform something that is very similar to those of popup/popunder scripts, performs various other logics including tracking outbound link clicks, and then "prevent default" actions of browsers.

Such logic is included in a file `https://vk.com/js/al/common.js`, in the body `onDocumentClick` function. 

Popup Blocker blocks the first part, so a notification is triggered, but at the same time the subsequent "prevent default" operation is blocked, so the link is navigated as it should.

I will add vk.com to default exclusions, as the page is already using complex logics which can be modified in future, and there is no guarantee that such logic will always be distinguishable from popup/popunder scripts.
