### ISSUE TITLE
An option to hide pop-up blocked notifications on a website

### ISSUE THREAD

**Issue by viper3444** [AdguardTeam/PopupBlocker#59]
Please, you could not add an option that would hide any notification of a blocked popup. Thank you

**Comment by vozersky** [comment]
could you please elaborate on your request a little bit?

**Comment by viper3444** [comment]
Yes, I want you to optionally add an option that disables notifications about blocked popup.

**Comment by lancelot-moon** [comment]
@ameshkov 
Hi,
Is it still unable to selectively set Popup Blocker run in the background without annoying notifications?
May you add the option?
Thanks.

**Comment by ameshkov** [comment]
There will be such an option on a per-site basis:
https://uploads.adguard.com/up04_j5xnh_ass_2.sketch.png

**Comment by lancelot-moon** [comment]
That's reported by a Taiwanese netfriend on PTT BBS.
Sometimes I answer their questions if they're lazy to contact with AdGuard support team.
Thanks for your kind service and hard working!

I like your this article on blog.
https://blog.adguard.com/en/the-chronicle-of-adguard/

It's not easy.
I believe that it'll get better and better.

B/R

**Comment by seanl-adg** [comment]
"Silence" option was implemented in https://github.com/AdguardTeam/PopupBlocker/commit/c77637aac61ab63792df59939fe36b975311cdd8. The release will be available soon.
