### ISSUE TITLE
rapidvideo.com

### ISSUE THREAD

**Issue by SebaK666** [AdguardTeam/PopupBlocker#61]
Script on Rapidvideo.com few week ago working perfect. No popup, no redirects - like Openload, but last weeks something change. Video working when script is active, but no working video scroll slider. When disable script and refresh rapidvideo.com slider of course working, but again opens new windows and redirects. It is possible fix this? Add Rapidvideo to whitelist not resolve problem.
Example link:
https://www.rapidvideo.com/v/FLHD1DY4YV

**Comment by SebaK666** [comment]
Browser: Firefox ESR 52.4, 
System: Windows XP, 
Greasemonkey 3.17 (4.0 is not not supported for my version Firefox), 
Adblocker: Adblock Plus 2.8.2, 
Filters: EasyList, EasyPrivacy, Fanboy Social Blocking List, Adblocj & uBlock polish, AakList (Anti-Adblock Killer filters)
Popup blocker: Adguard Popup Blocker 2.1.9
Greasemonkey scripts: Ads Bypasser, Anti Blocker Killer Reek, Handy Image and some less important

**Comment by aspasskaya** [comment]
Hi,
I cant repro this issue. (PopupBlocker 2.5.13)
@SebaK666 are problems still reproducible? Please, send a working link.
