### ISSUE TITLE
The pop-up blocker blocks external links in Thunderbird

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/PopupBlocker#66]
ID: 1618841

>  When I open my email in Thunderbird and click on a link, nothing happens. The border of the Thunderbird window flashes, as if it's getting ready to switch into Firefox for me, but nothing else happens after that. I can copy the link location and paste it into Firefox and everything loads as expected, but nothing clicks to open.

We suggested disabling the pop-up blocker and it helped. 

ID: 1620021
The similar problem, waiting for details, will update later. UPD: This customer uses EDGE for accessing her AOL mailbox.

**Comment by zebrum** [comment]
can not repro with firefox.
@vozersky can you try?
@evgeniy-ADG any additional info? is it any link from any letter or some specific?

**Comment by evgeniy-ADG** [comment]
> Using Internet Explorer on Windows 10, since the release of the new Comcast.net email user interface, any click on a link is being blocked by adguard pop up blocker. To stop this behavior, I disabled filtering on the Comcast mali website. I also clicked reinstall on adblocker, popup blocker and WOT extensions, plus unchecked pop up blocker extension, It wasn't until I disabled filtering for connect.xfinity.com/appsuite page that pop ups were no longer blocked.

ID: 1723621

**Comment by zzebrum** [comment]
@Eugene-Savenko were there any complaints about Comcast.net and popupblocker recently?

**Comment by Eugene-Savenko** [comment]
@zzebrum no

**Comment by zzebrum** [comment]
reopen if needed.
