### ISSUE TITLE
nrj-play.fr - false positive

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/PopupBlocker#73]
PopupBlocker blocks the facebook connect button (http://www.nrj-play.fr/cherie25/replay/sous-les-jupons-de-l-histoire-la-belle-otero).

![image](https://user-images.githubusercontent.com/10995998/35187108-dbce0554-fe1e-11e7-8c45-05f3d0d87bae.png)

Log:

[www.nrj-play.fr-1516475888823.log](https://github.com/AdguardTeam/PopupBlocker/files/1649191/www.nrj-play.fr-1516475888823.log)

**Comment by seanl-adg** [comment]
Fixed by https://github.com/AdguardTeam/PopupBlocker/commit/25a6416315a6513c8b67a976ae9da512de1d8721
