### ISSUE TITLE
Twitch.tv embedded player - false positive

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/PopupBlocker#75]
Steps to reproduce:

1. Go here - http://fandom.wikia.com/articles/pokemon-brick-bronze-free-fan-made-pokemon-mmo-roblox
2. Click on Twitch button in video player.

![image](https://user-images.githubusercontent.com/29142494/35390080-7ad4ebea-01da-11e8-8600-d139021fd76c.png)

![image](https://user-images.githubusercontent.com/29142494/35390095-8c098916-01da-11e8-995e-ee7b7f515d70.png)

**Comment by seanl-adg** [comment]
This is another react issue like https://github.com/AdguardTeam/PopupBlocker/issues/70

**Comment by ameshkov** [comment]
@seanl-adg is it possible to exclude twitch?

**Comment by seanl-adg** [comment]
I did it in a pull request, please check.

**Comment by seanl-adg** [comment]
Fixed by https://github.com/AdguardTeam/PopupBlocker/commit/25a6416315a6513c8b67a976ae9da512de1d8721
