### ISSUE TITLE
Can't download/update dev build in AdGuard for Windows

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/PopupBlocker#78]
Can't download the dev build using the url (https://AdguardTeam.github.io/PopupBlocker/popupblocker.user.js)

Same for Assistant dev build (https://adguardteam.github.io/AdguardAssistant/assistant.user.js).

Hope that's not an issue caused by AdGuard for Windows.

![image](https://user-images.githubusercontent.com/10995998/35643557-f9dcb530-06c6-11e8-908d-2c2e7827ff9a.png)

![image](https://user-images.githubusercontent.com/10995998/35643578-08581af0-06c7-11e8-830a-b39fa77b7429.png)

**Comment by ameshkov** [comment]
It seems that Github is having issues right

**Comment by seanl-adg** [comment]
I suppose this is caused by deprecation of TLS 1.0/1.1 on GitHub scheduled on February 1st.
https://githubengineering.com/crypto-deprecation-notice/

**Comment by ameshkov** [comment]
Good catch!
