### ISSUE TITLE
ebay - false positive

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/PopupBlocker#79]
The original report:
https://www.wilderssecurity.com/threads/adguard-blocking-paypal.400236/

Check out the screenshot:
https://www.wilderssecurity.com/threads/adguard-blocking-paypal.400236/#post-2735441

I guess we can safely add both paypal and ebay to exclusions.

**Comment by seanl-adg** [comment]
This is another jQuery issue. I think we should resolve such issues once and only once by using more intrusive measures. Also, please inform user in the forum about whitelisting feature, the user shouldn't have to restore system image for that issue.

**Comment by ameshkov** [comment]
I mean that we'd better resolve it with a minor patch right now (as well as twitch and tinder), and then solve it properly in a major update.

**Comment by seanl-adg** [comment]
Fixed by https://github.com/AdguardTeam/PopupBlocker/commit/25a6416315a6513c8b67a976ae9da512de1d8721
