### ISSUE TITLE
deezer.com - false positive

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/PopupBlocker#80]
Steps to reproduce:

1. Go here - https://www.deezer.com/
2. Click on Facebook button

<details><summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/29142494/35688540-b3805c08-0771-11e8-935a-9de0e2b987e0.png)

![image](https://user-images.githubusercontent.com/29142494/35688575-c1daece6-0771-11e8-8359-be0185b04957.png)

</details>

**Comment by seanl-adg** [comment]
React issue

**Comment by seanl-adg** [comment]
Fixed with https://github.com/AdguardTeam/PopupBlocker/commit/25a6416315a6513c8b67a976ae9da512de1d8721
