### ISSUE TITLE
A wrong word on oneskyapp.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/PopupBlocker#82]
@vbagirov 

It's "execution", not "exectution"
The original string is right.
But someone applied a wrong word instead of a correct word.

<details><summary>Screenshot</summary>

![image](https://i.imgur.com/upS9fef.png)
</details><br/>

B/R

**Comment by seanl-adg** [comment]
I uploaded a corrected phrase. Thank you for notifying us!
