### ISSUE TITLE
Make the extension icon interactive

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/PopupBlocker#84]
To make it interactive, you need to use the `browserAction` API:
https://developer.chrome.com/extensions/browserAction

The icon can be in two different states depending on whether the current tab is on the whitelist or not.

* Regular state: orange icon, it means that the website is not on the whitelist.
* Disabled state: gray icon, the website is on the whitelist.

Click on the extension icon switches the website state (either adds it to the whitelist or removes from it).

**Comment by seanl-adg** [comment]
Could you provide me gray icons? I currently have 16, 48, 128 sized orange icons.

**Comment by ameshkov** [comment]
> Could you provide me with gray icons? I currently have 16, 48, 128 sized orange icons.

Hm, I've set up a reminder for tomorrow.

Btw, Chrome is able to gray out the icon by itself:
https://uploads.adguard.com/up04_c18ob_Popup_Blocker_by_AdGuard_Beta_-_Chrome_Web_Store.png

I wonder if there an option to do it on purpose.

**Comment by ameshkov** [comment]
That one is done
