### ISSUE TITLE
knuddels.de - false positive

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/PopupBlocker#85]
Click the facebook button (https://www.knuddels.de/)

![image](https://user-images.githubusercontent.com/10995998/36166014-98f31400-10f1-11e8-85fd-d60e9bc4c006.png)

[www.knuddels.de-1518545536499.log](https://github.com/AdguardTeam/PopupBlocker/files/1721083/www.knuddels.de-1518545536499.log)

**Comment by seanl-adg** [comment]
React issue

**Comment by seanl-adg** [comment]
Fixed by https://github.com/AdguardTeam/PopupBlocker/commit/25a6416315a6513c8b67a976ae9da512de1d8721
