### ISSUE TITLE
chatovod.ru - false positive

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/PopupBlocker#86]
Steps to reproduce:
1. Go to http://chatovod.ru/
2. Click on user's name
3. Click on any icon

<details>

![image](https://user-images.githubusercontent.com/8361299/36304959-4a096828-131a-11e8-9beb-49b6616d19f8.png)

</details>

Current behavior: nothing happens;
Expected behavior: new window 

<details>

![image](https://user-images.githubusercontent.com/8361299/36304941-3be26592-131a-11e8-990b-96609a2d77ab.png)

</details>

**Comment by seanl-adg** [comment]
I will add `chatovod.ru/` to default whitelist.

**Comment by seanl-adg** [comment]
Done in https://github.com/AdguardTeam/PopupBlocker/commit/669c801a5b8b42fed2934543f9d48e8b1ae2c5f8

**Comment by karina-archazh** [comment]
Checked: all popup windows are available
