### ISSUE TITLE
Extension settings page

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/PopupBlocker#96]
@kaprielov please fix the first three points of this issue. You can find the code and the build instructions here: `projects/EXTENSIONS/repos/popup-blocker/pull-requests/22/overview`.

1. The page layout is not compatible with Chrome's `options_ui`, this needs to be fixed.
2. Remove the header and the close button: https://uploads.adguard.com/up04_um341_Extensions.png
3. We need help icons next to each section name: https://uploads.adguard.com/up04_icko2_Extensions.png
4. Leave two settings section: "Allowed" and "Silenced"

### Allowed

Domains listed in this section are allowed as targets OR as popup sources at the same time.

### Silenced

Popups are blocked silently on domains listed in this section.

**Comment by kaprielov** [comment]
@ameshkov can you tell me, what exactly are you mean about first item? If I understood correctly, `options_ui` is necessary for declare option page but it does working.

**Comment by ameshkov** [comment]
@kaprielov regarding the first point, just check how it looks like in the extension options. The content is centered vertically and it shouldn't be like that.

**Comment by kaprielov** [comment]
the first point is fixed

**Comment by seanl-adg** [comment]
@kaprielov could you check the first issue again with the current HEAD?

**Comment by seanl-adg** [comment]
This is a source code for chrome "Options Version 2" -- https://cs.chromium.org/chromium/src/chrome/browser/resources/md_extensions/options_dialog.js

According to it, it only sets a height of an option dialog once and does not change further even if its content changes.

>        // Only handle the 1st instance of 'preferredsizechanged' event, to get
>        // the preferred size.

**Comment by ameshkov** [comment]
This means we may need to have a fixed container height in the case of a Chrome's options page.

**Comment by seanl-adg** [comment]
https://github.com/AdguardTeam/PopupBlocker/commit/c77637aac61ab63792df59939fe36b975311cdd8
