### ISSUE TITLE
PopupBlocker  v2.2.2 issues with the test page

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/PopupBlocker#98]
1.

Preconditions:
Userscript installed to Adguard for Win
Chrome browser release  

**Artificial click on anchor 1** - popup is not being blocked

2.

Preconditions:
Userscript installed to Adguard for Win
Firefox browser release  

**Using temporary frame 2** - popup is not being blocked

3.

Preconditions:
Userscript installed to Adguard for Win
Edge browser release 

**Artificial click on anchor 1** - popup is not being blocked
**Using temporary frame 2** - empty i-frame appears on the page

**Comment by seanl-adg** [comment]
Should be fixed with https://github.com/AdguardTeam/PopupBlocker/commit/19e41c08c15ecc736437af9d60f6377e7af7c95f
