### ISSUE TITLE
http://rustorka.com/ - unconditional redirect at authorization

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/PopupBlocker#99]
It happens only once per day.
Maybe Russian proxy is required to reproduce the issue.
I recommend to record har when you open this site.

**Comment by aspasskaya** [comment]
I cant repro this issue. (PopupBlocker 2.5.13)
@Alex-302 are problems still reproducible?

**Comment by Alex-302** [comment]
Please check with the rule `@@||rustorka.com^$jsinject`
